#!/usr/bin/env bash
# Copies the shared logic and config into both runtimes:
#   apps-script/  — the calendar job (also gets the private settings)
#   web/shared/   — the web page (never gets the private settings)
#
# The copies are GENERATED. Line 2 of each records a hash of its body, and the
# sync refuses to overwrite a copy whose body no longer matches: that means
# someone edited the copy instead of shared/ or config/, and the edit would be
# lost silently. Move the change into shared/, delete the copy, re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

hash_of() { shasum -a 256 | cut -d' ' -f1; }

emit() {
  local dest="$1" body="$2"
  if [ -f "$dest" ]; then
    local recorded actual
    recorded="$(sed -n 2p "$dest" | sed -E 's/^\/\/ sha256:([0-9a-f]+).*$/\1/')"
    actual="$(tail -n +3 "$dest" | hash_of)"
    if [ "$recorded" != "$actual" ]; then
      echo "REFUSING: $dest was edited by hand. Move the change into shared/ or config/, delete the copy, re-run." >&2
      exit 1
    fi
  fi
  mkdir -p "$(dirname "$dest")"
  {
    echo "// GENERATED by scripts/sync_shared.sh — do not edit. Edit shared/ or config/ instead."
    echo "// sha256:$(hash_of < "$body")"
    cat "$body"
  } > "$dest"
  # Verify the copy landed intact.
  [ "$(tail -n +3 "$dest" | hash_of)" = "$(hash_of < "$body")" ] || { echo "Copy check failed: $dest" >&2; exit 1; }
  echo "  wrote $dest"
}

# JSON config → a script that defines a global. Parsing here fails loudly on a typo.
as_js() {
  local json="$1" global="$2" out="$3"
  node -e '
    const fs = require("fs");
    const [json, name] = process.argv.slice(1);
    const value = JSON.parse(fs.readFileSync(json, "utf8"));
    process.stdout.write("var " + name + " = " + JSON.stringify(value, null, 2) + ";\n" +
      "if (typeof module !== \"undefined\" && module.exports) module.exports = " + name + ";\n");
  ' "$json" "$global" > "$out"
}

[ -f "$ROOT/config/private.json" ] || { echo "Missing config/private.json (share list + alert email)." >&2; exit 1; }

as_js "$ROOT/config/tariff.json" STROOM_CONFIG "$TMP/config.js"
as_js "$ROOT/config/private.json" STROOM_PRIVATE "$TMP/private-config.js"

echo "apps-script/"
for f in classify.js describe.js fetch-prices.js; do emit "$ROOT/apps-script/$f" "$ROOT/shared/$f"; done
emit "$ROOT/apps-script/config.js" "$TMP/config.js"
emit "$ROOT/apps-script/private-config.js" "$TMP/private-config.js"

echo "web/shared/"
for f in classify.js describe.js fetch-prices.js; do emit "$ROOT/web/shared/$f" "$ROOT/shared/$f"; done
emit "$ROOT/web/shared/config.js" "$TMP/config.js"
