// GENERATED by scripts/sync_shared.sh — do not edit. Edit shared/ or config/ instead.
// sha256:ffb0c2e47d94475c6db2003472d4086e2990bcafd40f90ccfb5f735304119a52
/*
 * Stroom — the words: event titles, descriptions and price formatting.
 * Dutch word as a label, the information in English.
 *
 * Single source of truth — edit here in shared/ only.
 */
var StroomText = (function () {
  'use strict';

  function core() {
    return typeof StroomCore !== 'undefined' ? StroomCore : require('./classify.js');
  }

  const KIND = {
    free: { emoji: '🆓', nl: 'Gratis', en: 'Free power' },
    cheap: { emoji: '🟢', nl: 'Goedkoop', en: 'Cheap' },
    expensive: { emoji: '🔴', nl: 'Duur', en: 'Avoid' },
    best: { emoji: '⭐', nl: 'Beste tijd', en: 'Best' },
  };
  const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  function euro(v) {
    const r = Math.round(v * 100) / 100;
    return (r < 0 ? '−' : '') + '€' + Math.abs(r).toFixed(2);
  }

  function euroRange(a, b) {
    const lo = euro(a);
    const hi = euro(b);
    if (lo === hi) return lo;
    return a < 0 || b < 0 ? lo + ' to ' + hi : lo + '–' + hi.slice(1);
  }

  // A window ending exactly at the end of dateStr reads "24:00", not "00:00".
  function timeLabel(ms, dateStr) {
    const lp = core().localParts(ms);
    if (lp.date !== dateStr && lp.hour === 0 && lp.minute === 0 && ms === core().dayRange(dateStr).end) return '24:00';
    return core().pad(lp.hour) + ':' + core().pad(lp.minute);
  }

  function span(startMs, endMs, dateStr) {
    return timeLabel(startMs, dateStr) + '–' + timeLabel(endMs, dateStr);
  }

  function dayLabel(dateStr) {
    const [y, m, d] = dateStr.split('-').map(Number);
    const wd = new Date(Date.UTC(y, m - 1, d)).getUTCDay();
    return WEEKDAYS[wd] + ' ' + d + ' ' + MONTHS[m - 1];
  }

  function joinWords(words) {
    return words.length < 2 ? words.join('') : words.slice(0, -1).join(', ') + ' and ' + words[words.length - 1];
  }

  function title(kind, block, plan, config) {
    const k = KIND[kind];
    const when = span(block.startMs, block.endMs, plan.date);
    if (kind === 'best') {
      return k.emoji + ' ' + k.nl + ' · ' + k.en + ' ' + config.bestWindowHours + 'h ' + when + ' · ' + euro(block.average);
    }
    return k.emoji + ' ' + k.nl + ' · ' + k.en + ' ' + when + ' · ' + euroRange(block.min, block.max);
  }

  // "Dishwasher (eco)" + 3h → "Dishwasher (eco, 3h)"; "Dryer" + 2h → "Dryer (2h)".
  function applianceLabel(appliance) {
    const name = appliance.name;
    return name.endsWith(')')
      ? name.slice(0, -1) + ', ' + appliance.hours + 'h)'
      : name + ' (' + appliance.hours + 'h)';
  }

  function costLines(kind, block, plan, config) {
    const compareWithBest = kind === 'expensive';
    const lines = [compareWithBest
      ? 'Cost of one run, started at ' + timeLabel(block.startMs, plan.date) + ' vs. the cheapest start that day:'
      : 'Cost of one run, started at ' + timeLabel(block.startMs, plan.date) + ' vs. the most expensive start that day:'];
    plan.appliances.filter((a) => a.appliance.shiftable).forEach((a) => {
      const here = core().runAt(plan.hours, a.appliance, block.startMs);
      const other = compareWithBest ? a.best : a.worst;
      if (!here || !other) return;
      lines.push('• ' + applianceLabel(a.appliance) + ': ' + euro(here.cost) +
        ' · ' + euro(other.cost) + ' at ' + timeLabel(other.startMs, plan.date));
    });
    return lines;
  }

  function hourList(plan) {
    return plan.hours.map((h) => {
      const k = KIND[h.tier];
      return h.label + '  ' + euro(h.allIn) + (k ? '  ' + k.emoji : '');
    });
  }

  function description(kind, block, plan, config, source) {
    const words = joinWords(config.appliances.filter((a) => a.shiftable).map((a) => a.word));
    const extras = joinWords(config.appliances.filter((a) => !a.shiftable).map((a) => a.word));
    const start = timeLabel(block.startMs, plan.date);
    const end = timeLabel(block.endMs, plan.date);
    const n = config.bestWindowHours;
    // The live page link goes first, so it shows without expanding the event on a phone.
    const lines = config.pageUrl ? ['⚡ Now and tomorrow at a glance: ' + config.pageUrl, ''] : [];

    if (kind === 'free') {
      lines.push('The market price is below zero — you only pay energy tax and Eneco’s fee.');
      lines.push('Good time for: ' + words + '.');
      if (extras) lines.push('Also a good moment to charge ' + extras + ' and power banks.');
    } else if (kind === 'cheap') {
      lines.push('Good time for: ' + words + '.');
    } else if (kind === 'expensive') {
      lines.push('Avoid starting: ' + words + '.');
      if (start === '00:00') lines.push('Wait until ' + end + '.');
      else if (end === '24:00') lines.push('Start before ' + start + '.');
      else lines.push('Start before ' + start + ', or wait until ' + end + '.');
      if (plan.best) {
        lines.push('Cheapest ' + n + ' hours that day: ' + span(plan.best.startMs, plan.best.endMs, plan.date) +
          ' (' + euro(plan.best.average) + ' per kWh).');
      }
    } else if (kind === 'best') {
      lines.push(plan.stats.flat
        ? 'Flat day — prices barely change, so timing matters little.'
        : 'No clearly cheap hours that day.');
      lines.push('These are the cheapest ' + n + ' hours: good for ' + words + '.');
    }

    lines.push('');
    lines.push.apply(lines, costLines(kind, block, plan, config));
    lines.push('');
    lines.push('Prices ' + dayLabel(plan.date) + ' (€ per kWh, all-in):');
    lines.push.apply(lines, hourList(plan));
    lines.push('');
    lines.push('⚡ Stroom · Eneco Dynamisch · market prices: EPEX day-ahead' + (source ? ' via ' + source : ''));
    return lines.join('\n');
  }

  function eventsForPlan(plan, config, source) {
    const events = plan.windows.map((w) => ({
      kind: w.tier,
      startMs: w.startMs,
      endMs: w.endMs,
      title: title(w.tier, w, plan, config),
      description: description(w.tier, w, plan, config, source),
    }));
    if (plan.showBest) {
      events.push({
        kind: 'best',
        startMs: plan.best.startMs,
        endMs: plan.best.endMs,
        title: title('best', plan.best, plan, config),
        description: description('best', plan.best, plan, config, source),
      });
    }
    return events.sort((a, b) => a.startMs - b.startMs);
  }

  const api = {
    KIND: KIND,
    euro: euro,
    euroRange: euroRange,
    timeLabel: timeLabel,
    span: span,
    dayLabel: dayLabel,
    title: title,
    description: description,
    eventsForPlan: eventsForPlan,
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  return api;
})();
